// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.NumberBaseConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("input_value")]
        public string InputValue { get; set; }

        [JsonProperty("input_base")]
        public long InputBase { get; set; }

        [JsonProperty("input_base_name")]
        public string InputBaseName { get; set; }

        [JsonProperty("decimal_value")]
        public long DecimalValue { get; set; }

        [JsonProperty("output_value")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long OutputValue { get; set; }

        [JsonProperty("output_base")]
        public long OutputBase { get; set; }

        [JsonProperty("output_base_name")]
        public string OutputBaseName { get; set; }
    }
}
